const router = require('express').Router();
const controller = require('../controllers/expenseController');
const { asyncHandler } = require('../utils/http');
router.use(require('../middlewares/authMiddleware'));
router.get('/', asyncHandler(controller.list));
router.post('/', asyncHandler(controller.create));
router.get('/:id', asyncHandler(controller.get));
router.put('/:id', asyncHandler(controller.update));
router.patch('/:id', asyncHandler(controller.update));
router.delete('/:id', asyncHandler(controller.remove));
module.exports = router;
